packages:
  - packages/*
  - examples/*
catalog:
  "@automerge/subduction": "^0.20.1"
  '@automerge/automerge': ^3.3.2
  '@types/debug': ^4.1.13
  debug: ^4.4.3
  uuid: ^14.0.1
minimumReleaseAgeExclude:
  - '@automerge/subduction@0.20.1'
