packages:
  - packages/*
  - examples/*
allowBuilds:
  esbuild: false
catalog:
  "@automerge/subduction": "^0.21.0"
  '@automerge/automerge': ^3.3.2
  '@types/debug': ^4.1.13
  debug: ^4.4.3
  uuid: ^14.0.1
overrides:
  "@automerge/subduction": "file:../subduction/subduction_wasm"
